<?php

/**
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Enigma plugin              |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

*/

$labels = array();
$labels['server_caldav'] = 'Configuration of CalDAV server';
$labels['url_base'] = 'Specify the url of your calDAV server ';
$labels['login'] = 'Specify your server login';
$labels['password'] = 'Specify your password';
$labels['save_error_msg'] = 'Your information are incorrect or incomplete';
$labels['main_calendar'] = 'Specify your default calendar';
$labels['calendar_choice'] = 'Choose your default calendar (the left radio button) and the other calendar you may use (the right checkboxes), \n
Warning : If you change url / login / password your preferences will be forgotten';

$labels['same_hour_meeting'] = 'You already have one or several meeting during this period: ';
$labels['connect_error_msg'] = 'Connection with CalDAV server failed';
$labels['attendee'] = 'Attendees: ';
$labels['all_day'] = 'All day';

?>
