<?php

/**
 * +-----------------------------------------------------------------------+
 * | Localization file of the Roundcube Webmail Enigma plugin              |
 * |                                                                       |
 * | Copyright (C) The Roundcube Dev Team                                  |
 * |                                                                       |
 * | Licensed under the GNU General Public License version 3 or            |
 * | any later version with exceptions for skins & plugins.                |
 * | See the README file for a full license statement.                     |
 * +-----------------------------------------------------------------------+
 */


$labels = array();
$labels['server_caldav'] = 'Configuration serveur CalDAV';
$labels['url_base'] = 'Indiquez l\'url de votre serveur calDAV';
$labels['login'] = 'Indiquer votre login utilisé sur le serveur';
$labels['password'] = 'Indiquez votre mot de passe';
$labels['save_error_msg'] = 'Vos informations sont incorrectes et/ou incomplètes';
$labels['main_calendar'] = 'Veuillez indiquer votre calendrier par default';
$labels['calendar_choice'] = 'Attention : si vous modifiez votre url / login / mot de passe vos préférences seront oubliées. \n
 Veuillez choisir votre calendrier par default  ainsi que les calendriers que vous serez amené à utilisé ';
$labels['connect_error_msg'] = 'La connection avec votre server CalDAV à échouée';
$labels['invitation'] = 'Vous avez reçu une invitation :';
$labels['same_hour_meeting'] = 'Vous avez deja un ou plusieur rendez vous durant cette periode :';
$labels['attendee'] = 'Participants: ';
$labels['reply_all'] = 'Répondre à tous';
$labels['previous_meeting'] = ' Rendez vous précédent: ';
$labels['next_meeting'] = 'Rendez vous suivants: ';
$labels['all_day'] = 'Toute la journée';
$labels['successfully_saved'] = 'Cet événement à été ajouté à votre agenda';
$labels['something_happened'] = "L'enregistrement de cet événement ne s'est pas passé comme prévu";
$labels['confirm'] = 'Confirmer';
$labels['tentative'] = 'Confirmer Provisoirement';
$labels['decline'] = "Décliner l'invitation";
$labels['confirmed'] = 'Confirmé';
$labels['tentatived'] = 'Confirmé Provisoirement';
$labels['declined'] = "L'invitation est déclinée";
$labels['location'] = "Lieu: ";
$labels['description'] = "Description: ";
$labels['chose_calendar'] = "Evénement à ajouter au calendrier: ";
$labels['repeated_event'] = "L'évenement se répète à plusieurs occurences: ";
$labels['use_this_calendar'] = "Utiliser le calendrier ";
$labels['make_this_calendar_default1'] = "Selectionner le calendrier ";
$labels['make_this_calendar_default2'] = " par défaut";


?>
