<?php

/**
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Enigma plugin              |
 |                                                                       |
 | Copyright (C) The Roundcube Dev Team                                  |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+


 */


$labels = array();
$labels['server_caldav'] = 'Configuration serveur CalDAV';
$labels['url_base'] = 'Indiquez l\'url de votre serveur calDAV';
$labels['login'] = 'Indiquer votre login utilisé sur le serveur';
$labels['password'] = 'Indiquez votre mot de passe';
$labels['save_msg'] = 'Vos information ont été sauvegardée';
$labels['save_error_msg'] = 'Vos informations sont incorectes et/ou incomplètes';

$messages = array();
$messages['sigvalid'] = 'Verified signature from $sender.';
?>
